services:
  - type: web
    name: tax-payment-mcp-server
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    healthCheckPath: /health
